name: Release Compiled PDF 
on:
  push:
    branches:
      - main
    tags:
      - '*.*.*'

jobs:
  build_latex:
    permissions: 
      contents: write

    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          root_file: main.tex
          working_directory: report
      - name: Move and rename
        run: |

          mv main.pdf report/build/MSc_group_q.pdf
      - name: Commit report
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          file_pattern: '*.pdf'
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.sha }}
          release_name: Release ${{ github.sha }}
          draft: false
          prerelease: false