name: LaTex to PDF

on:
  push:
    branches:
    - main

jobs:
  build_latex:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4
      - name: latex2pdf
        id: compile-latex-document
        uses: xu-cheng/latex-action@v3
        with:
          root_file: main.tex
          args: -pdf -file-line-error -interaction=nonstopmode -shell-escape
          latexmk_use_lualatex: false  
          latexmk_shell_escape: true
          extra_system_packages: "biber"
      - name: Commit report
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          file_pattern: '*.pdf'
