name: Build LaTeX document
on: [push]
jobs:
  build_latex:
    permissions: 
      contents: write
    runs-on: ubuntu-latest
    steps:
    
      - name: Set up Git repository
        uses: actions/checkout@v4
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v3
        with:
          root_file: 
            report/main.tex
          
          texlive_version: 2024
          continue_on_error: true
          args: -biber