name: LaTeX to PDF
on:
  push:
    branches: 
      - main
    tags:
       - '*'
jobs:
  build_latex:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4

      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v3
        with:
          root_file: main.tex
          args: -pdf -file-line-error -interaction=nonstopmode
          working_directory: .
          latexmk_use_xelatex: false
          latexmk_shell_escape: true
          # Extra packages needed for bibliography
          extra_system_packages: "biber"

      - name: Create output directory
        run: mkdir -p output
        
      - name: Move PDF to output directory
        run: mv main.pdf output/main.pdf
        
      - name: Upload PDF to the workflow tab
        uses: actions/upload-artifact@v4
        with:
          name: PDF Output
          path: output/main.pdf
          if-no-files-found: error

      - name: Commit report
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          file_pattern: 'output/*.pdf'
          commit_message: "Build LaTeX document"
