name: LaTeX to PDF
on:
  push:
    branches: 
      - main
    tags:
       - '*'
jobs:
  build_latex:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4

      - name: Generate Book PDF
        uses: hspaans/latexmk-action@v2.0.0
        with:
          format: pdf
          filename: main.tex

      - name: Upload PDF
        uses: actions/upload-artifact@v4
        with:
          name: compiled-book
          path: main.pdf
