name: Release Compiled PDF 
on:
  push:
    branches:
      - main
jobs:
  build_latex:
    permissions: 
      contents: write

    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          root_file: main.tex
          working_directory: report
      - name: Move and rename
        run: |

          mv report/main.pdf report/build/MSc_group_q.pdf
      - name: Commit report
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          file_pattern: '*.pdf'
      - name: Set Timestamp
        id: timestamp
        run: echo "TIMESTAMP=$(date +"%Y%m%d%H%M%S")" >> $GITHUB_ENV
      - name: Get new commit SHA
        id: get_sha
        run: echo "COMMIT_SHA=$(git rev-parse HEAD)" >> $GITHUB_ENV
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.TIMESTAMP }}
          release_name: Release ${{ env.TIMESTAMP }}
          draft: false
          prerelease: false
          commitish: ${{ env.COMMIT_SHA }}